### ISSUE TITLE
really long pauses

### ISSUE THREAD

**Issue by crmackay** [mangecoeur/document-outline#16]
Whenever I have document-outline enabled. I find Atom giving me long (several second) pauses when I am actively typing. 

I suspect it is because I am writing "long" documents...but these are not that long. The one I am working on now is a markdown file with 229 lines and 22159 characters. Many of my lines are really long, since I have softwrapping on, and I just keep a paragraph on a single soft-wrapped line for convenience. 

I don't have too many headings though (one top level, 2 second level, 1 third level).

Let me know what other information I can provide to help out.

**Comment by mangecoeur** [comment]
I've made a bunch of improvements in the latest version, can you tell me if you still have this problem? Also let me know what is your operating system?
Currently, I'm using this on my macbook pro also with long documents (200+ lines/30000+ characters) without such pauses, although I did have the problem in the past that over time I would start to see some slowdown which I hopefully fixed with the newest updates.

**Comment by crmackay** [comment]
I using version 1.4.1 of the document-outline package on OSX 10.

The version of Atom is 1.16.0.

I still find that when I have "document-outline" enabled I get very sluggish typing the longer it is enabled. This happens even if I enable then quit and reopen atom.  I keep trying it because i like being able to navigate by heading, but after a while I will need to disable it for a bit to type, and then turn it back on when I need to do editing.

**Comment by mangecoeur** [comment]
Sorry you're still having this problem I realised I have it too after typing for a while, spent time today trying to figure out what could be causing it and I think I found it, want to test my solution a bit more but should have a fix out in the coming days.




Get Outlook for Android






From: Chris MacKay

Sent: Tuesday, 18 April, 21:41

Subject: Re: [mangecoeur/document-outline] really long pauses (#16)

To: mangecoeur/document-outline

Cc: mangecoeur, Comment



I using version 1.4.1 of the document-outline package on OSX 10.


The version of Atom is 1.16.0.


I still find that when I have "document-outline" enabled I get very sluggish typing the longer it is enabled. This happens even if I enable then quit and reopen atom. I keep trying it because i like being able to navigate by heading, but after a while I will need to disable it for a bit to type, and then turn it back on when I need to do editing.

**Comment by crmackay** [comment]
sounds good! Like I said, I still use your package, because it is great, but have to use it selectively instead of keeping it on all the time, which obviously would be preferred. 

Thanks for making this!

**Comment by mangecoeur** [comment]
Ok I think i finally cured this issue, some code was erroneously being triggered on every keypress which was causing the editor event system to get clogged up. Seems find now and have pushed a new update with the changes. Will close the issue for now, let me know if you are still having problems.

**Comment by crmackay** [comment]
just wanted to say thanks! the last few updates have certainly improved performance!

**Comment by mangecoeur** [comment]
Thanks! Frankly I was kinda surprise a little plugin to show a tree-view could cause so many performance issues, turns out Atom can be pretty fickle.
