### ISSUE TITLE
Odd colour issues

### ISSUE THREAD

**Issue by philip-hodder** [mangecoeur/document-outline#2]
Hi again

Since the latest (1.0.2) update the colour scheme seems very light. I liked it before, with h1, h2 etc building up the shades of grey. But now the h3/h4 level backgrounds make the titles almost indistinguishable against it. This is with the atom-dark theme.

**Comment by mangecoeur** [comment]
Sorry to hear that. Something about Atom 1.12 broke the way I used to do it, so I tried my best to re-create that effect (clearly without enough success). I will try again to make it work as preferred.

**Comment by mangecoeur** [comment]
@philip-hodder p.s. are you using atom-dark for both UI and syntax?

**Comment by philip-hodder** [comment]
No worries! And yes atom-dark for both. I just tried switching both to atom-light and get the same effect although 'inverted' if you see what I mean.

**Comment by mangecoeur** [comment]
yeah it seems especially problematic on the atom-dark/light themes. As a workaround I can suggest using the One-* UI or Material UI themes with whatever syntax theme you like (I use Pen Paper coffee but the atom-dark and -light seem to behave a lot better) but I will try to make this better in due course.

**Comment by mangecoeur** [comment]
I've decided for now to only support the 'modern' themes because the others are too quirky. Fixes for those themes which don't break the modern ones are welcome.

**Comment by pierre-haessig** [comment]
Hello,

I just met an issue with Atom 1.25, document-outline 2.1.1 (on Linux), using One Light for the UI and One Dark for syntax. The text of outline is a very light gray which is not very readable. I understand that supporting each exotic theme combination is painful so I'd just like to know if you consider the One Light+Dark combo as acceptable or exotic. (Since I'm really not a familiar with Atom internals, I don't know what is a "modern" theme, as you mentioned in you last message in April 2017).

best, Pierre

![atom markdown outline color issue](https://user-images.githubusercontent.com/1010404/37713748-27a91bbc-2d18-11e8-964d-113c01223581.png)
