### ISSUE TITLE
Asciidoc sections not supported

### ISSUE THREAD

**Issue by danyill** [mangecoeur/document-outline#26]
The full range of Asciidoc section options doesn't appear to be supported, particularly those beginning with `=`, `==` and so on.

The document outline generates no table of contents for these. It does generate them for an Asciidoc when they use the Markdown compatible sections `#`, `##` etc.

See the [Asciidoctor user manual]( http://asciidoctor.org/docs/user-manual/#sections) and the [Asciidoc user guide](http://www.methods.co.nz/asciidoc/userguide.html#X17).

It would be great if this extension could support Asciidoc more fully. Thanks for your work so far. Happy to provide further detail and carry out testing.

**Comment by mangecoeur** [comment]
Someone else contributed Asciidoc support and i'm not familiar with the format, so not sure what is and isn't set up. I don't have a huge amount of time to work on file formats that i don't use regularly, but would welcome contributions.

The very best would be to use a lightwieght JS asciidoc parser similar to commonmarkjs, which can give much more reliable identification of headings (instead of just regex hacks). Not sure if this exists (I am aware there is a JS version of asciidoctor but it seems to be a heft beast).
