### ISSUE TITLE
feature request (with implementation)

### ISSUE THREAD

**Issue by CBenghi** [mangecoeur/document-outline#45]
Hello @mangecoeur,

I love your extension, I think it's great.
I use it for markdown editing of large academic papers and felt the need to have visual indicators of tasks to address.

I've attempted a first implementation that you can look at: https://github.com/CBenghi/document-outline/commit/794ddd01d17274e1b5867916292656b0291219af

On my system it looks like this:

![image](https://user-images.githubusercontent.com/5476273/31316591-57156a66-ac28-11e7-91ba-b10c7c71e915.png)

There's a test file ```test_statusIcons.md``` in the ```specs``` folder, with some comments on how to use.
I'm quite new to atom, I'm happy to change the code as needed to include any feedback.

Best,
Claudio

**Comment by mangecoeur** [comment]
Hi @CBenghi , looks really nice. 

I had a look at the code - is it your intention that a heading can have several icons or will it always be just one? If it is just one, it would be better to set it on the heading as a string property with a few possible options (e.g. `todoStatus = 'done'`) rather than have many boolean properties, because if you have lots of booleans, you end up with many possible combinations of states and you have to test every combination to make sure it works!

**Comment by CBenghi** [comment]
I see what you mean.
Yes, it was intended for multiple icons. I'm not 100% sure of what would be a neat implementation. 

I might have rushed to talk about this, but I felt some conversation was useful to understand if it's a generalised use case or just something that works for me...

One thing that has come to mind is that counting of todos/others might also be useful to estimate the efforts, and possibly also group them when a branch is collapsed, but this would replace each boolean with two int (direct + children counts).

I'd like to find a generalisation that might serve more people...
Any comment welcome.
Claudio

**Comment by mangecoeur** [comment]
I think you did great to share this, I'm happy if you are willing to work
on it. I think a cleaner and more extensible implementation if you want to
support multiple icons is to have a list of tags which get added to the
heading, e.g. `heading.tags =[]` then add the tags e.g.
`heading.tags.push('done')` .  The tag names can be the css class names so
that it's trivial after to add the list of tags to the list of css styles
of the element so that it gets its icon

**Comment by salim-b** [comment]
> I use it for markdown editing of large academic papers and felt the need to have visual indicators of tasks to address.

It looks great what I see on the screenshot and in the `test_statusIcons.md` 👍  That's a really useful feature (at least for me).

Just a simple remark: The normal in-text (i.e. not enclosed in comments) recognition of the words that trigger the icons should be optional (and probably disabled by default). Otherwise there will most certainly be false positives (which will be very annoying) 😉

**Comment by CBenghi** [comment]
@salim-b,
thanks for your comment. 

I'm not sure it'd be easy to exclude the body of work as the parser we are using now is a bit brute. But I'll give a look at false positives.

If you wish, you can have a play with the code at https://github.com/CBenghi/document-outline/tree/feature/HighlightTodo.

I updated it with some regularioty, but I'll take more time to propose a PR to the official package until I get a stable(ish) framework.

Best,
Claudio

**Comment by salim-b** [comment]
> If you wish, you can have a play with the code at https://github.com/CBenghi/document-outline/tree/feature/HighlightTodo.

Thanks for the invitation, but I don't have any capacities for this atm... :/

With "false positives" I mostly mean that regular Markdown user might not like having icons pop-up in all their headers and bodies which contain any of the relevant keywords (done, next etc.) 🙂
