### ISSUE TITLE
Feature request: movable sections

### ISSUE THREAD

**Issue by ProjectRamo** [mangecoeur/document-outline#87]
I didn't see this feature request before, so I am adding it.

It would be neat to be able to move sections around, by dragging and dropping them in the outline view and having the markdown move around to reflect the changes in the outline.

I think this would be a killer feature since people can move sections (chapters, sections, scenes) more easily.

**Comment by matthewmerendo** [comment]
I second this request... and third it, if I can!

**Comment by kurisu-gh** [comment]
I fourth it! I've been jumping around various LaTeX editing environments and I'm surprised not many environments provide this feature. I was just on the VSCode LaTeX-Workshop repo requesting this feature but got shot down because VSCode's outline panel is read-only.

Here's what I requested over there (but is certainly relevant here):

**Describe the solution you'd like**
An intuitive way to manipulate the document elements in the Outline panel.
For example:
* Drag-and-drop to re-order your document elements or change their hierarchy level
* Cut/copy/paste/delete elements directly in the Outline panel
* Insert new document elements directly from the outline panel
* Select multiple document elements for cut/copy/paste/delete, hierarchy promotion/demotion
* A mechanism to filter out elements in the Outline panel by hierarchy level (e.g. show only sub-sections) or by keyword

**Describe alternatives you've considered**
I have tried both [TexStudio](https://www.texstudio.org/) and [TeXlipse](https://projects.eclipse.org/proposals/eclipse-texlipse). They both have outline/structure editing feature to some extent as can be seen in these screenshots for [TexStudio (structure panel)](https://i.imgur.com/onU7YdK.png) and [TeXlipse (outline panel)](https://i.imgur.com/ZOyEBnj.png). TeXlipse actual outline panel capabilities are described [here](http://texlipse.sourceforge.net/manual/outline.html). TeXlipse comes close in the functionality I like but I don't like using the Eclipse IDE. 

Similarly, Microsoft Word does a decent job of this via their navigation panel.

I definitely agree, this would be a killer feature. As far as I know, there is no document outline/structure editor for Markdown, LaTeX, etc. out there that does this well.

**Comment by mangecoeur** [comment]
I've thought of this, and I'm sorry to say it's not going to happen. Long story short is that it's much more difficult to implement than you might think, and it kinda defeats the point of using a 'lite' text editor - you are better using a full WYSIWYG editor like Word or TexStudio etc if you want this kind of functionality.
